name: project1
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  hive: ^2.2.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
